---

- name: Deploy python "Hello World" web service
  hosts: web
  become: yes
  become_method: sudo
  tasks:
    - name: Ensure python is installed
      apt: 
        name: python3
        state: present
      become: yes

    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present
      become: yes

    - name: Copy the requirements.txt file
      copy:
       src: /requirements.txt
       dest: /home/ubuntu/hello_world/requirements.txt

    - name: Install required python packages
      pip:
        requirements: /home/ubuntu/hello_world/requirements.txt
        executable: pip3
      become: yes

    - name: Copy the app.py file
      copy:
        src: /my-app.py
        dest: /home/ubuntu/hello_world/my-app.py

    - name: Start the web service
      shell: |
        cd /home/ubuntu/hello_world
        nohup python3 my-app.py > output.log 2>&1 &
      args:
        chdir: /home/ubuntu/hello_world 
